### ISSUE TITLE
MutableVolatileDirtySet - collection modified while enumerating

### ISSUE THREAD

**Issue by haraldsteinlechner** [vrvis/aardvark#18]
Evaluate gets called recursively (wtf), which destroyes enumeration of the set (although locked).
Don't know how to fix non-symptomatically - for the moment i use list enumeration (which is faster in this case anyways).

**Comment by haraldsteinlechner** [comment]
symptomatic fix in: 6845501343a16ab1503ab50da77d59644843e88e, see https://github.com/vrvis/aardvark/issues/19

**Comment by krauthaufen** [comment]
Solved with new implementation for ASets???

**Comment by haraldsteinlechner** [comment]
should be fixed
