### ISSUE TITLE
AdaptiveSet passThrough optimization on Remove does not work

### ISSUE THREAD

**Issue by haraldsteinlechner** [vrvis/aardvark#19]
in Remove:
```
                | None ->
                    r.RemoveOutput ri
                    readers.Remove ri |> ignore

                    if readerCount = 2 then
                        let r = readers |> Seq.exactlyOne
                        r.SetPassThru(true, false)
                        onlyReader <- Some r

            readerCount <- readerCount - 1
```

Seq.exactlyOne fails because of concurrent modification on readers if remove is called concurrently by the GC. For the moment i disabled the check and stay in non-pass-through

**Comment by haraldsteinlechner** [comment]
nothing helps here, it is very common that GC destroys all kinds of mutable state. Either more locking or less finalizers

**Comment by haraldsteinlechner** [comment]
tried to fix via locking (lock mutable vars onlyReader et al). Although those vars only occur privately in aset i still have appearently concurrent modifications. totally crazy

**Comment by haraldsteinlechner** [comment]
6845501343a16ab1503ab50da77d59644843e88e at elast symptomatically solves some issues.
firstly, remove shall only decrement readers count if the reader is a valid reader (and can thus be counted).
Secondly, via finalizers, remove calls can be unsynchronized, therefore the additional (possibly nested) lock in local remove.
Thirdly, MutableVolatileDirtySet now performs eval on a copy. This is not totally threadsafe but at least does not produce lost updates (eventually).

**Comment by krauthaufen** [comment]
Should be working right now...

**Comment by krauthaufen** [comment]
Test in aardvark.base.incremental.tests
