### ISSUE TITLE
EmitReader collection modified

### ISSUE THREAD

**Issue by haraldsteinlechner** [vrvis/aardvark#9]
override x.ComputeDelta() =
            let content = x.Content
            match reset with
                | Some c ->
                    //Interlocked.Increment(&resetCount) |> ignore
                    reset <- None
                    let add = c |> Seq.filter (not << content.Contains) |> Seq.map Add
                    let rem = content |> Seq.filter (not << c.Contains) |> Seq.map Rem

                    Seq.append add rem |> Seq.toList

CSet emits deltas, while compute delta lazily pulls this stuff. Think bout locking here

**Comment by krauthaufen** [comment]
Three possibilities:
1) Solve via locking the input set (which must then be passed down to its EmitReaders) (what if user locks on set?)
2) persist the set when emitted (expensive)
3) lock on the set itself and adjust cset to respect that lock (complicated)

**Comment by krauthaufen** [comment]
should be solved in a66b32331437dbe6284817fd3967e46ba05f58a3

Untested yet...
